### ISSUE TITLE
Incompatibility with NoExpensive

### ISSUE THREAD

**Issue by istust** [Fourmisain/TaxFreeLevels#1]
The mod is incompatible with the mod NoExpensive and the game crashes on startup.

**Comment by Fourmisain** [comment]
Known incompatibility, it's because NoExpensive uses an [`@Overwrite` to change `AnvilScreenHandler.updateResult()`](https://github.com/Enaium-FabricMC/NoExpensive/issues/4), so there is nothing I can do about it.

You can use Anvil Fix instead, that works without any issues.

I'm sure there are other mods out there which make Infinity and Mending compatible, not sure about Multishot and Piercing though.

**Comment by Fourmisain** [comment]
Looks like this incompatibility was fixed in https://github.com/Enaium-FabricMC/NoExpensive/commit/837ea3c8fdd44584af64bc04e84f10fdbfa0294d (version 1.2.0 for 1.17)
