### ISSUE TITLE
Crash with Balanced Enchanting

### ISSUE THREAD

**Issue by DerShendi** [Fourmisain/TaxFreeLevels#11]
heres the logs and sorry if im coming off as rude but it wont start when tax free is enabled
[2022-07-15-2.log.gz](https://github.com/Fourmisain/TaxFreeLevels/files/9116774/2022-07-15-2.log.gz)

**Comment by Fourmisain** [comment]
Hm... at first I thought it was something with Enigmatic Legacy but its mixins shouldn't be an issue (not a crash issue at least).

Instead it looks like there's some ASM patching going on with those messages:

> [02:29:02] [pool-3-thread-1/INFO]: Patching RepairContainer#updateRepairOutput
[02:29:02] [pool-3-thread-1/INFO]: Successfully removed the anvil level cap.
[02:29:02] [pool-3-thread-1/INFO]: Patching RepairContainer#updateRepairOutput
[02:29:02] [pool-3-thread-1/INFO]: Successfully allowed nbt-unbreakable items in the anvil.
[02:29:02] [pool-3-thread-1/INFO]: Patching net/minecraft/inventory/container/RepairContainer

A bit of googling brings me to Apotheosis, which is confusing to me since I'm sure it's compatible with Tax Free Levels, at least on 1.18, maybe that's just an issue with 1.16?

Hm... yeah, looks like the [container_repair](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/resources/coremods/container_repair.js) and [mythics_anvil](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/resources/coremods/mythics_anvil.js) coremods are only part of their 1.16 branch but not their 1.18 branch.

Oof, do I need to do some legacy patching again? :face_exhaling:

**Comment by Fourmisain** [comment]
Hm... I can't actually reproduce the issue, I'm running Apotheosis, Tax Free Levels and Enigmatic Legacy and everything seems to be working just fine.

What versions are you using? Here's what I used:

Forge 36.2.35
[TaxFreeLevels 1.3.2-beta](https://www.curseforge.com/minecraft/mc-mods/tax-free-levels/files/3724678)
[Apotheosis-1.16.5-4.8.99F](https://www.curseforge.com/minecraft/mc-mods/apotheosis/files/3779410)
[EnigmaticLegacy-2.11.12](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy/files/3758580)
and also
[Placebo-1.16.5-4.7.0](https://www.curseforge.com/minecraft/mc-mods/placebo/files/3750838)
[curios-forge-1.16.5-4.0.8.2](https://www.curseforge.com/minecraft/mc-mods/curios/files/3725386)
[Patchouli-1.16.4-53.3](https://www.curseforge.com/minecraft/mc-mods/patchouli/files/3847029)

**Comment by Fourmisain** [comment]
Are you running All the Mods 6?
If so, you need to remove Balanced Enchanting as it's conflicting with this mod and it has the same functionality (minus compatibility with some other mods) anyway.

**Comment by Fourmisain** [comment]
From the CurseForge comments it's confirmed that this exact error stems from the incompatibility with Balanced Enchanting and the solution is just to remove it.
