### ISSUE TITLE
Enchanting Changes compatiblity

### ISSUE THREAD

**Issue by RYUKxAnime** [Fourmisain/TaxFreeLevels#15]
can you make this compatible with the enchanting changes mod 
https://www.curseforge.com/minecraft/mc-mods/enchanting-changes

**Comment by RYUKxAnime** [comment]
mainly for 1.17.1 fabric smp

**Comment by Fourmisain** [comment]
Oh, there's an issue I missed!

Just checked what's causing the incompatibility and it looks like Enchanting Changes completely overrides the vanilla anvil behavior meaning there is nothing I can do to make both mods compatible - though at least the enchanting seems to work.

You'd have to take that request up to the maker of the mod, hamarb123 - if they're still maintaining the mod; it's been almost 2 years since the last update.
