### ISSUE TITLE
Incompatibility with Apotheosis 7.2.0

### ISSUE THREAD

**Issue by MrFastZombie** [Fourmisain/TaxFreeLevels#21]
Minecraft 1.20.1
Tax Free Levels 1.3.6
Apotheosis 7.2.0
NeoForge 47.1.84
Log: https://mclo.gs/VrIHx84

When Apotheosis and Tax Free Levels are installed together, there is a crash at start up that gives this error
```
[16:12:43] [pool-4-thread-1/FATAL] [mixin/]: Mixin apply failed taxfreelevels-forge.mixins.json:FlattenAnvilCostMixin -> net.minecraft.world.inventory.AnvilMenu: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Specified index 0 for @ModifyArg is invalid for args (Lnet/minecraft/world/entity/player/Player;I), expected I on net/minecraft/world/inventory/AnvilMenu::taxfreelevels$flattenAnvilCost [INJECT Applicator Phase -> taxfreelevels-forge.mixins.json:FlattenAnvilCostMixin -> Apply Injections ->  -> Inject -> taxfreelevels-forge.mixins.json:FlattenAnvilCostMixin->@ModifyArg::taxfreelevels$flattenAnvilCost(I)I]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 0 for @ModifyArg is invalid for args (Lnet/minecraft/world/entity/player/Player;I), expected I on net/minecraft/world/inventory/AnvilMenu::taxfreelevels$flattenAnvilCost [INJECT Applicator Phase -> taxfreelevels-forge.mixins.json:FlattenAnvilCostMixin -> Apply Injections ->  -> Inject -> taxfreelevels-forge.mixins.json:FlattenAnvilCostMixin->@ModifyArg::taxfreelevels$flattenAnvilCost(I)I]
```

I also saw this warning, no idea if it is related
`[16:12:34.135] [main/WARN] [loading.FMLConfig/CORE]: Configuration file F:\Games\PolyMC Instances\Tax Free Levels - Apotheosis\.minecraft\config\fml.toml is not correct. Correcting `

**Comment by Fourmisain** [comment]
Aha, it looks like Apotheosis added their own ["optimal cost" implementation](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/java/dev/shadowsoffire/apotheosis/mixin/AnvilMenuMixin.java#L21-L30)!
It's different from mine, which bases the cost on level 30 instead of level 0, so it'll be drasticly cheaper for small original level costs.

Proper compatibility would require a change on Apotheosis' side, probably involving MixinExtras and I don't think anyone is really going to care for the difference, so I just disabled the conflicting mixin when both mods run together.

Also, just a heads up: NeoForge 1.20.1 isn't officially supported. You are using the Forge version, which just happens to be compatible. Forge 1.20.2+ mods will not be compatible with NeoForge 1.20.2+, so don't get too used to the idea of using NeoForge as a drop-in replacement for Forge.
(That said, I'll always support NeoForge.)

1.3.7 is up!

**Comment by Fourmisain** [comment]
Actually, maybe I can change the implementation in their Placebo mod, no need to try to fix the mixin conflict!

**Comment by Fourmisain** [comment]
Okay, I think this should be good.
I noticed I broke the mod detection in the last update too, oops!

1.3.8 is up!
