### ISSUE TITLE
Mixin crash with Spectrum 1.7.9

### ISSUE THREAD

**Issue by DaFuqs** [Fourmisain/TaxFreeLevels#27]
I tested a few modpacks that use Spectrum and noticed that you mixin into it to apply your changes to the Bedrock Anvil, too. Neat!
With Spectrum 1.7.9 I made some changes to the Bedrock Anvil GUI to closer match the 1.20 vanilla code.

But because they were substantial changes, that broke your mixin. Sorry!

The changes: https://github.com/DaFuqs/Spectrum/commit/c0dc6cd2ca6435a05cce5c61f4f4f2456d7c2f35

**Comment by Fourmisain** [comment]
Ah, thanks for the info!
Gonna have a loot at it right now.

P.S.
I love Spectrum, easily one of my all-time favorite mods!

**Comment by Fourmisain** [comment]
Aha!
I was confused for a bit since the relevant `canTakeOutput` and `addExperienceLevels` code didn't actually seem to have changed and rebuilding my mod without changes magically fixed everything.

The things is: Going from `HandledScreen` to `ForgingScreen` means the `canTakeOutput` method now actually overrides the vanilla method, so it'll be remapped to `method_24923`, _that's_ the breaking change.

I guess I'll take some time to rewrite some stuff using MixinExtras while I'm at it (those mixins are _old_).

**Comment by DaFuqs** [comment]
Perfect, thank you!

**Comment by Fourmisain** [comment]
Aight, made it backwards compatible too! Thanks again!
