### ISSUE TITLE
Config file?

### ISSUE THREAD

**Issue by Soggyshorts** [Fourmisain/TaxFreeLevels#29]
I was really hoping to find a config file I could tweak. The goal is to remove all tax and basically replace level costs with straight xp costs. 
I get that paying thousands to go from level 68 to 33 in your example of vanilla sucks, but I find it unacceptable to even pay a single xp extra.

**Comment by Fourmisain** [comment]
That's planned. (And a lot of work due to having to do config sync on multiple platforms.)

See the discussion in #28 for why I based everything off of level 30.
(**tl;dr** old versions were based off level 0 and I found many costs to be unreasonably small)

If you want **all** costs to be independent from player level, you could also use something like [Linear Levels](https://modrinth.com/mod/linear-levels).
When every level is worth the same XP, so are the costs.
(Though that mod by default still has some scaling for better balancing. If you set it to linear, I'd set it to around 46.5 XP per level so you roughly reach level 30 at the same time as vanilla.)

**Comment by Fourmisain** [comment]
Finally done!
Version 1.4 now has a config and some other large changes (basing costs off of level 0 by default, no "Too Expensive!"). Give the changelog a read.

It's only out for 1.21 for now. Hopefully the backports won't be too taxing (no pun intended).
