### ISSUE TITLE
Crash in 1.18.2

### ISSUE THREAD

**Issue by jklw10** [Fourmisain/TaxFreeLevels#9]
could be a mod collision but crash reports is hard to read. mixin problem though
[latest.log](https://github.com/Fourmisain/TaxFreeLevels/files/8886150/latest.log)
.

**Comment by Fourmisain** [comment]
Looks like a conflict between limitless.
Tax Free Levels is meant as a (partial) replacement for it, so it makes little sense to use both.

The reason why I made this mod in the first place is because limitless is very invasive in its changes, it has many incompatibilities and even breaks datapacks.

Needless to say, I won't try to add compatibility for it, so choose either mod, not both.

**Comment by jklw10** [comment]
yep, over enchantment mod is a good replacement.
